### ISSUE TITLE
Hide ACF Menu

### ISSUE THREAD

**Issue by MaximeCulea** [BeAPI/bea-plugin-defaults#10]
Following #9, we should find a way to hide ACF Menu for non-developping sites.

As a starting point, [this](https://github.com/BeAPI/bea-plugin-defaults/pull/9#issuecomment-394075092) could be a workaround.
But we have to keep in mind that there could be others way to do it, we have to discuss about it.

**Comment by TweetPressFr** [comment]
> ok guys but what's the point of a github repository if we only use our own constants ?

**Comment by Rahe** [comment]
Putting this here https://github.com/BeAPI/bea-plugin-defaults/pull/9#issuecomment-394315649
We use out own constants because there is no WordPress constants that are filling our needs.
Sage and Bedrock are using `WP_ENV` and we are now on every project as they are part of the config files.

ACF interface is for creating fields from admin (and some tools) and isn't related to the debugging process, as our fields are exported to PHP/JSON they aren't displayed into any environments except development mode (and some particular cases).

So keep using `ACF_LITE` is an acceptable solution
- not introducing any other constant
- have a back compatibility
- may already be widely used by most of the community

**Comment by MaximeCulea** [comment]
I feel that you @TweetPressFr and @Rahe are sharing the same point of view about the constant name.
In my opinion, it could be the good one 👌

**Comment by TweetPressFr** [comment]
re ^^

**Comment by MaximeCulea** [comment]
@Rahe so ? 🤗

**Comment by Rahe** [comment]
Go for `ACF_LITE` imho

**Comment by Rahe** [comment]
Added on the ACF file
